rethinkdb:
     restart: always
     # Note: you must add this file to the root of your project in order for compose to work.
     env_file: .docker-compose.env
     image: rethinkdb
     ports:
         - "8080"
         - "28015"
         - "29015"

controller:
     restart: always
     # Note: you must add this file to the root of your project in order for compose to work.
     env_file: .docker-compose.env
     build: .
     dockerfile: Dockerfile
     entrypoint: /bin/bash
     command: -c "make all && cd controller && ./controller -D server --rethinkdb-addr rethinkdb:28015 -d tcp://myd-vm23183.hpswlabs.adapps.hp.com:3375"
     links:
         - rethinkdb
     volumes:
         - .:/go/src/github.com/shipyard/shipyard
     volumes_from:
         - media
     ports:
         - "8082:8080"
