postgres:
  hostname: postgres
  image: postgres:9.4.5
  environment:
    - PGDATA=/var/lib/postgresql/data/pgdata
    - POSTGRES_PASSWORD=postgres
  volumes:
   - /DATA/postgres/pgdata:/var/lib/postgresql/data/pgdata
  ports:
   - "5432:5432"

clair:
  image: quay.io/coreos/clair:master
  environment:
     http_proxy: "http://web-proxy.bbn.hp.com:8080"
     https_proxy: "http://web-proxy.bbn.hp.com:8080"
     no_proxy: "127.0.0.1,localhost,mydyumserver,.hp.com,.hpe.com,.hpecorp.net,.hpeswlab.net,.hpqcorp.net,16.59.0.0"
  links:    
   - postgres
  volumes: 
    - ./clair_config:/config:ro
    - /tmp:/tmp
  command: "--config=/config/config.yaml" 
  ports:
   - "6060:6060"
   - "6061:6061"
   - "9279:9279"