rethinkdb:
    restart: always
    image: rethinkdb:2.2
    ports:
        - "8083:8080"
        - "8084:28015"
        - "8085:29015"
    environment:
        no_proxy: "localhost,127.0.0.1,proxy,swarm,media,rethinkdb,myd-vm23183.hpswlabs.adapps.hp.com"

proxy:
    restart: always
    image: ehazlett/docker-proxy:latest
    volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
        - "2375"
    command: -D
    environment:
        no_proxy: "localhost,127.0.0.1,proxy,swarm,media,rethinkdb,myd-vm23183.hpswlabs.adapps.hp.com"

swarm:
    restart: always
    image: swarm:1.1.3
    command: m --host tcp://0.0.0.0:2375 proxy:2375
    links:
        - "proxy:proxy"
    ports:
        - "2375"
    environment:
        no_proxy: "localhost,127.0.0.1,proxy,swarm,media,rethinkdb,myd-vm23183.hpswlabs.adapps.hp.com"

media:
    restart: always
    build: .
    entrypoint: /bin/bash
    dockerfile: Dockerfile.build
    command: -c "make media && sleep infinity"
    working_dir: /go/src/github.com/shipyard/shipyard
    volumes:
        - "./controller/static:/go/src/github.com/shipyard/shipyard/controller/static"
    environment:
        no_proxy: "localhost,127.0.0.1,proxy,swarm,media,rethinkdb,myd-vm23183.hpswlabs.adapps.hp.com"

controller:
    restart: always
    build: .
    dockerfile: Dockerfile.build
    entrypoint: /bin/bash
    command: -c "make all && ./shipyard -D server --rethinkdb-addr rethinkdb:28015 -d tcp://swarm:2375"
    links:
        - rethinkdb
        - swarm
    volumes:
        - .:/go/src/github.com/shipyard/shipyard
    volumes_from:
        - media
    ports:
        - "8082:8080"
    environment:
        no_proxy: "localhost,127.0.0.1,proxy,swarm,media,rethinkdb,myd-vm23183.hpswlabs.adapps.hp.com"
