version: '2'

services:
  rethinkdb:
      env_file: .env
      restart: always
      image: rethinkdb:2.2
      ports:
          - "8083:8080"
          - "8084:28015"
          - "8085:29015"
      networks:
        - sy_network

  proxy:
      env_file: .env
      restart: always
      image: ehazlett/docker-proxy:latest
      volumes:
          - "/var/run/docker.sock:/var/run/docker.sock"
      ports:
          - "2375"
      command: -D
      networks:
        - sy_network
  swarm:
      env_file: .env
      restart: always
      image: swarm:1.2.0
      command: m --host tcp://0.0.0.0:2375 proxy:2375
      ports:
          - "2375"
      depends_on:
        - proxy
      networks:
        - sy_network

# TODO: .env must contain swarm master node to connect to
  controller:
      env_file: .env
      restart: always
      image: controller-sa
      volumes_from:
          - proxy
      ports:
          - "8082:8080"
          - "9279"
      depends_on:
        - rethinkdb
      networks:
        - sy_network

  postgres:
    hostname: postgres
    image: postgres:9.4.5
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=postgres
    volumes:
     - /DATA/postgres/pgdata:/var/lib/postgresql/data/pgdata
    ports:
     - "5432:5432"
    networks:
      - sy_network

  clair:
    env_file: .env
    image: quay.io/coreos/clair:v1.1.0
    volumes:
      - ./clair_config:/config:ro
      - /tmp/clair-data:/tmp
    entrypoint: /bin/bash
    command: -c "sleep 30 && clair --config=/config/config.yaml"
    ports:
     - "6060:6060"
     - "6061:6061"
    depends_on:
      - postgres
    networks:
      - sy_network

networks:
  sy_network: