version: '2'

services:
  rethinkdb:
      env_file: .env
      restart: always
      image: rethinkdb:2.2
      ports:
          - "8080"
          - "28015"
          - "29015"
      networks:
        - ui_test

  proxy:
      env_file: .env
      restart: always
      image: ehazlett/docker-proxy:latest
      volumes:
          - "/var/run/docker.sock:/var/run/docker.sock"
      ports:
          - "2375"
      command: -D
      networks:
        - ui_test
  swarm:
      env_file: .env
      restart: always
      image: swarm:1.2.0
      command: m --host tcp://0.0.0.0:2375 proxy:2375
      ports:
          - "2375"
      networks:
        - ui_test

  controller:
      env_file: .env
      restart: always
      build:
        context: .
        dockerfile: Dockerfile.build
      entrypoint: /bin/bash
      command: -c "make all && ./shipyard -D server --rethinkdb-addr rethinkdb:28015 -d tcp://swarm:2375"
      volumes:
          - .:/go/src/github.com/shipyard/shipyard
      volumes_from:
          - proxy
      ports:
          - "8080"
          - "9279"
      depends_on:
        - rethinkdb
      networks:
        - ui_test

  postgres:
    hostname: postgres
    image: postgres:9.4.5
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=postgres
    volumes:
     - /tmp/postgres:/var/lib/postgresql/data/pgdata
    ports:
     - "5432"
    networks:
      - ui_test

  clair:
    env_file: .env
    image: quay.io/coreos/clair:v1.1.0
    volumes:
      - ./clair_config:/config:ro
      - /tmp/clair-data:/tmp
    entrypoint: /bin/bash
    command: -c "sleep 30 && clair --config=/config/config.yaml"
    ports:
     - "6060"
     - "6061"
    depends_on:
      - postgres
      - controller
    networks:
      - ui_test

networks:
  ui_test:
